### ISSUE TITLE
Domain with trailing slash not filtered

### ISSUE THREAD

**Issue by phixofor** [Cederfjard/unvisiter#1]
When adding a domain in the options, a trailing slash won't filter that domain. 

My suggestion is to automatically filter away trailing slashes in the input.

**Comment by Cederfjard** [comment]
Nice catch, thank you @phixofor! Added a fix here: 84c84b29ac82120544ad1a6aaad759bfb78c9177

Instead of filtering trailing slashes I'm extracting the hostnames, so that it works even if you add an URL with a path.
